### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by samselikoff** [romulomachado/ember-cli-string-helpers#175]
Hi, thanks for this great lib!

Is there a changelog anywhere?

**Comment by romulomachado** [comment]
Hey, @samselikoff! There isn't. 😬 

There hasn't been a lot of changes since this lib was extracted from `ember-composable-helpers`. Most of the updates are related to dependencies with one or two bugfixes here and there. 

This year I'd like to take more time to dig through it and possibly add new features. I'll keep this issue open, so I don't forget to add a changelog.

**Comment by samselikoff** [comment]
Cool, thanks! At the least could you jot down what the breaking changes for v3 and v4 were?

**Comment by romulomachado** [comment]
`v3` dropped support for node 6; 
`v4` required build options to be moved to `ember-cli-build.js` (prev on `config/environment.js`)

**Comment by samselikoff** [comment]
Sweet. I'd suggest adding these to Releases page so folks can at least find em!

- 3.0: https://github.com/romulomachado/ember-cli-string-helpers/releases/tag/v3.0.0
- 4.0: https://github.com/romulomachado/ember-cli-string-helpers/releases/tag/v4.0.0

Just a quick edit with Breaking change: heading and those points would be super helpful <3

**Comment by romulomachado** [comment]
@samselikoff Thanks for the suggestion! I just updated the releases pages.

**Comment by chbonser** [comment]
@romulomachado Sorry to revisit a closed ticket, but could you provide some insight on the breaking changes in 5 -> 6?

Thanks in advance!
